/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GroupUpdateGroupAttrs {
  method: "group.updateGroupAttrs";
  auth_type?: "ADMIN";
  group_name: string;
  attrs: {
    [k: string]: unknown;
  };
  to_del_attrs: unknown[];
}
