/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface McAddNewProvider {
  method: "mc.addNewProvider";
  auth_type?: "ADMIN";
  provider_type:
    | "Parspooyesh"
    | "Pishgaman"
    | "Rahyab"
    | "I-Email"
    | "ADP"
    | "Generic-HTTP"
    | "IBSngMessaging"
    | "Magfa"
    | "MihanSMSCenter"
    | "AsreFaraErtebat"
    | "AFE-WS";
  provider_name: string;
  msg_type: "SMS" | "E-Mail" | "Message To Admin" | "Message To User";
}
