/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ListOfDestinations = unknown[];
export type SourceSenderAddressPhoneNumberEmail = string;

export interface McReceive {
  method: "mc.receive";
  auth_type?: "ADMIN" | "NORMAL_USER" | "VOIP_USER";
  msg_info: {
    dst?: ListOfDestinations;
    msg_type?: "SMS" | "E-Mail" | "Message To Admin" | "Message To User";
    from?: SourceSenderAddressPhoneNumberEmail;
    body?: string;
    [k: string]: unknown;
  };
}
