/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface McRemoveEPGroupFromProvider {
  method: "mc.removeEPGroupFromProvider";
  auth_type?: "ADMIN";
  provider_id: number;
  end_point_group_id: number;
}
