/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SessionExpireSession {
  method: "session.expireSession";
  auth_type?: "ADMIN" | "NORMAL_USER" | "VOIP_USER";
  session_id: string;
}
