/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface IppoolGetIPpoolInfo {
  method: "ippool.getIPpoolInfo";
  auth_type?: "ADMIN";
  ippool_name: string;
}
