/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface LdapGetUserInfos {
  method: "ldap.getUserInfos";
  auth_type?: "ADMIN";
  starts_with: string;
}
