/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserCustomFieldDeleteCustomField {
  method: 'user_custom_field.deleteCustomField'
  auth_type: 'ADMIN'
  name: string
}
