/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PermLoadPermsFromAnotherAdmin {
  method: "perm.loadPermsFromAnotherAdmin";
  auth_type?: "ADMIN";
  admin_username: string;
  load_from_admin_username: string;
}
