/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PermCanDo {
  method: 'perm.canDo'
  auth_type?: 'ADMIN'
  perm_name: string
  admin_username: string
  params: unknown[]
}
