/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface VoucherSearchVoucher {
  method: "voucher.searchVoucher";
  auth_type: "ADMIN";
  conds: unknown;
  from: number;
  to: number;
  sort_by: "pin" | "voucher_id";
  desc: boolean;
}
