/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface VoucherVoucherAddBatch {
  method: "voucher.voucherAddBatch";
  auth_type: "ADMIN";
  batch_dict: unknown;
  pin_prefix: string;
  pin_len: number;
  serial_prefix: string;
  serial_start: number;
  count: number;
}
