/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface InvoiceSearchProformaInvoices {
  method: 'invoice.searchProformaInvoices'
  auth_type: 'ADMIN'
  conds: unknown
  _from: number
  to: number
  sort_by: 'issue_date' | 'user_id' | 'total_amount'
  desc: boolean
}
