/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TelephonySupportRecharge {
  method: "telephony_support.recharge";
  auth_type: "ADMIN";
  user_id: number;
  pin: string;
}
