/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface IspSetISPPageStyle {
  method: 'isp.setISPPageStyle'
  auth_type?: 'ADMIN'
  isp_id: number
  header_logo_ext: string
  header_logo_contents: string
  header_bg_color: string
  header_text_color: string
  footer_logo_ext: string
  footer_logo_contents: string
  footer_bg_color: string
  footer_text_color: string
  footer_msg: string
}
