/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface McGetUserActivationNumber {
  method: "mc.getUserActivationNumber";
  auth_type: "NORMAL_USER" | "VOIP_USER";
}
