/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface McUpdateAdminRemoteRequestAttrs {
  method: "mc.updateAdminRemoteRequestAttrs";
  auth_type: "ADMIN";
  remote_report_status: string;
  remote_report_command: string;
  allowed_requesters: string;
  attrs: unknown;
}
