/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface McUnAssingAllFromGroup {
  method: 'mc.unAssingAllFromGroup'
  auth_type: 'ADMIN'
  provider_name: string
  end_point_group_id: number
}
