/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserTemporaryExtendUsers {
  method: 'user.temporaryExtendUsers'
  auth_type: 'ADMIN'
  user_id: string
  temporary_extend_hours: number
  temporary_extend_credit: number
}
