/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserSaveSearchExpiredUsers {
  method: "user.saveSearchExpiredUsers";
  auth_type: "ADMIN";
  output_type: "csv" | "pdf";
  conds: unknown;
  order_by: "user_id" | "isp_id" | "group_id" | "creation_date" | "credit" | "Deposit";
  desc: boolean;
  basic: unknown[];
  attrs: unknown[];
}
