/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserBulkDeleteUser {
  method: 'user.bulkDeleteUser'
  auth_type: 'ADMIN'
  conds: unknown
  delete_comment: string
  del_connection_logs: boolean
  del_audit_logs: boolean
}
