/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserSearchUser {
  method: 'user.searchUser'
  auth_type: 'ADMIN'
  conds: unknown
  abs_exp_date_from?: string
  abs_exp_date_from_unit: 'jalali' | 'gregorian' | 'years' | 'months' | 'days' | 'hours' | 'minutes'
  abs_exp_date_to?: string
  abs_exp_date_to_unit: 'jalali' | 'gregorian' | 'years' | 'months' | 'days' | 'hours' | 'minutes'
  allow_recharge_by_voucher?: boolean
  allow_user_disconnect?: boolean
  assign_dns?: string
  assign_dns_op: 'like' | 'ilike' | 'starts_with' | 'ends_with' | 'equals'
  has_assign_ip?: boolean
  assign_ip?: string
  assign_ip_op: 'like' | 'ilike' | 'starts_with' | 'ends_with' | 'equals'
  has_assign_netmask?: boolean
  assign_netmask?: string
  assign_netmask_op: 'like' | 'ilike' | 'starts_with' | 'ends_with' | 'equals'
  has_assign_route_ip?: boolean
  assign_route_ip?: string
  assign_route_ip_op: 'like' | 'ilike' | 'starts_with' | 'ends_with' | 'equals'
  asterisk_did_number?: string
  asterisk_did_destination?: string
  asterisk_did_peer_address?: string
  auto_recharge?: boolean
  auto_renew?: boolean
  auto_renew_do_not_reset_credit?: boolean
  caller_id?: string
  caller_id_op: 'like' | 'ilike' | 'starts_with' | 'ends_with' | 'equals'
  charge?: unknown[]
  comment?: string
  comment_op: 'like' | 'ilike' | 'starts_with' | 'ends_with' | 'equals'
  name?: string
  name_op: 'like' | 'ilike' | 'starts_with' | 'ends_with' | 'equals'
  postal_code?: string
  postal_code_op: 'like' | 'ilike' | 'starts_with' | 'ends_with' | 'equals'
  phone?: string
  phone_op: 'like' | 'ilike' | 'starts_with' | 'ends_with' | 'equals'
  cell_phone?: string
  cell_phone_op: 'like' | 'ilike' | 'starts_with' | 'ends_with' | 'equals'
  email?: string
  email_op: 'like' | 'ilike' | 'starts_with' | 'ends_with' | 'equals'
  birthdate?: string
  birthdate_unit: 'jalali' | 'gregorian' | 'years' | 'months' | 'days' | 'hours' | 'minutes'
  birthdate_op: '=' | '>' | '<' | '>=' | '<='
  address?: string
  address_op: 'like' | 'ilike' | 'starts_with' | 'ends_with' | 'equals'
  has_connection_log_archive?: boolean
  creation_date_from?: string
  creation_date_from_unit: 'jalali' | 'gregorian' | 'years' | 'months' | 'days' | 'hours' | 'minutes'
  creation_date_to?: string
  creation_date_to_unit: 'jalali' | 'gregorian' | 'years' | 'months' | 'days' | 'hours' | 'minutes'
  credit?: number
  credit_op: '=' | '>' | '<' | '>=' | '<='
  credit_limit?: boolean
  custom_field_test_integer?: number
  custom_field_test_integer_op: '=' | '>' | '<' | '>=' | '<='
  custom_field_test_string?: string
  custom_field_test_string_op: 'like' | 'ilike' | 'starts_with' | 'ends_with' | 'equals'
  deny_change_password?: boolean
  deposit?: number
  deposit_op: '=' | '>' | '<' | '>=' | '<='
  deposit_recharge?: number
  deposit_recharge_op: '=' | '>' | '<' | '>=' | '<='
  email_address?: string
  email_address_op: 'like' | 'ilike' | 'starts_with' | 'ends_with' | 'equals'
  user_value_exp_from_creation_date_from?: string
  user_value_exp_from_creation_date_from_unit:
    | 'jalali'
    | 'gregorian'
    | 'years'
    | 'months'
    | 'days'
    | 'hours'
    | 'minutes'
  user_value_exp_from_creation_date_to?: string
  user_value_exp_from_creation_date_to_unit: 'jalali' | 'gregorian' | 'years' | 'months' | 'days' | 'hours' | 'minutes'
  user_value_exp_from_first_login_from?: string
  user_value_exp_from_first_login_from_unit: 'jalali' | 'gregorian' | 'years' | 'months' | 'days' | 'hours' | 'minutes'
  user_value_exp_from_first_login_to?: string
  user_value_exp_from_first_login_to_unit: 'jalali' | 'gregorian' | 'years' | 'months' | 'days' | 'hours' | 'minutes'
  exp_from_renew_user_value_from?: string
  exp_from_renew_user_value_from_unit: 'jalali' | 'gregorian' | 'years' | 'months' | 'days' | 'hours' | 'minutes'
  exp_from_renew_user_value_to?: string
  exp_from_renew_user_value_to_unit: 'jalali' | 'gregorian' | 'years' | 'months' | 'days' | 'hours' | 'minutes'
  exp_monthly_user_value_from?: string
  exp_monthly_user_value_from_unit: 'jalali' | 'gregorian' | 'years' | 'months' | 'days' | 'hours' | 'minutes'
  exp_monthly_user_value_to?: string
  exp_monthly_user_value_to_unit: 'jalali' | 'gregorian' | 'years' | 'months' | 'days' | 'hours' | 'minutes'
  first_login_from?: string
  first_login_from_unit: 'jalali' | 'gregorian' | 'years' | 'months' | 'days' | 'hours' | 'minutes'
  first_login_to?: string
  first_login_to_unit: 'jalali' | 'gregorian' | 'years' | 'months' | 'days' | 'hours' | 'minutes'
  real_first_login_from?: string
  real_first_login_from_unit: 'jalali' | 'gregorian' | 'years' | 'months' | 'days' | 'hours' | 'minutes'
  real_first_login_to?: string
  real_first_login_to_unit: 'jalali' | 'gregorian' | 'years' | 'months' | 'days' | 'hours' | 'minutes'
  group_name?: unknown[]
  in_ras_ippool?: string
  in_ras_ippool_op: 'like' | 'ilike' | 'starts_with' | 'ends_with' | 'equals'
  ippool?: unknown[]
  is_online?: boolean
  online_status?: string
  from: number
  to: number
  order_by:
    | 'normal_username'
    | 'voip_username'
    | 'user_id'
    | 'group_id'
    | 'creation_date'
    | 'owner_id'
    | 'credit'
    | 'deposit'
    | 'first_login'
    | 'serial'
    | 'serial_numeric'
  desc: boolean
}
