/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserKillUser {
  method: 'user.killUser'
  auth_type: 'ADMIN'
  user_id: string
  ras_ip: string
  unique_id_val: string
  kill?: boolean
}
