/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface OnlinePaymentPurgePayment {
  method: 'online_payment.purgePayment'
  auth_type?: 'ADMIN'
  payment_id: number
}
