/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TelephonySupportAuthenticate {
  method: "telephony_support.authenticate";
  auth_type?: "ADMIN";
  auth_by: "user_id" | "serial" | "voip_username" | "internet_username" | "phone";
  auth_id: string;
}
