/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TelephonySupportCheckInternetPassword {
  method: 'telephony_support.checkInternetPassword'
  auth_type?: 'ADMIN'
  user_id: number
  internet_password: string
}
