/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ReportSaveCreditChanges {
  method: "report.saveCreditChanges";
  auth_type: "ADMIN";
  conds: unknown;
  cols: unknown[];
  sort_by: "change_time" | "per_user_credit" | "isp_credit";
  desc: boolean;
  output_type: "csv" | "pdf";
}
