/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ReportGetSystemAuditLogs {
  method: 'report.getSystemAuditLogs'
  auth_type: 'ADMIN'
  conds: unknown
  from: number
  to: number
  sort_by: 'change_time' | 'object_id' | 'admin_id' | 'event' | 'category' | 'isp_id'
  desc: boolean
}
