/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ReportSavePrefixNameUsage {
  method: 'report.savePrefixNameUsage'
  auth_type: 'ADMIN'
  conds: unknown
  order_by: 'prefix_name' | 'prefix_code' | 'duration_sum' | 'count' | 'credit'
  desc: boolean
  output_type: 'csv' | 'pdf'
}
