/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ReportGetExpiredUsers {
  method: "report.getExpiredUsers";
  auth_type: "ADMIN";
  conds: unknown;
  from: number;
  to: number;
  sort_by:
    | "user_id"
    | "normal_username"
    | "voip_username"
    | "group_id"
    | "owner_id"
    | "creation_date"
    | "credit"
    | "deposit"
    | "first_login"
    | "serial"
    | "serial_numeric";
  desc: boolean;
}
