/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ReportGetOnlinePaymentReport {
  method: "report.getOnlinePaymentReport";
  auth_type: "ADMIN" | "NORMAL_USER" | "VOIP_USER";
  conds: unknown;
  from: number;
  to: number;
  sort_by:
    | "payment_id"
    | "gateway_id"
    | "unique_id"
    | "amount"
    | "payment_date"
    | "requester_id"
    | "requester_type"
    | "succeed";
  desc: boolean;
}
