/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ReportGetISPDepositChangeLogs {
  method: "report.getISPDepositChangeLogs";
  auth_type: "ADMIN";
  conds: unknown;
  from: number;
  to: number;
  sort_by:
    | "isp_deposit_change_admin_id"
    | "isp_deposit_change_isp_id"
    | "isp_deposit_change_time"
    | "isp_deposit_change_amount";
  desc: boolean;
}
