/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SystemNotificationGetNotifications {
  method: 'SystemNotification.getNotifications'
  auth_type: 'ADMIN'
  last_notifications?: number
  only_unread?: boolean
}
