/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BwAddInterface {
  method: 'bw.addInterface'
  auth_type: 'ADMIN'
  hostname: string
  interface_name: string
  comment: string
  host_type: 'Linux' | 'Mikrotik'
}
