/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BwAddLeafService {
  method: "bw.addLeafService";
  auth_type: "ADMIN";
  leaf_name: string;
  dst_ip: string;
  protocol: "tcp" | "udp" | "icmp" | "ip";
  filter: string;
  rate_kbits: number;
  ceil_kbits: number;
  priority: number;
}
