/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BwAddNode {
  method: 'bw.addNode'
  auth_type: 'ADMIN'
  hostname: string
  interface_name: string
  parent_id: number
  rate_kbits: number
  ceil_kbits: number
  priority: number
}
