/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BwDelLeafService {
  method: "bw.delLeafService";
  auth_type: "ADMIN";
  leaf_service_id: number;
  leaf_name: string;
}
