/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ReportGetPrefixNameUsage {
  method: 'report.getPrefixNameUsage'
  auth_type?: 'ADMIN'
  conds: {
    group_by?: {
      [k: string]: unknown
    }[]
    [k: string]: unknown
  }
  from: number
  to: number
  order_by: 'prefix_name' | 'prefix_code' | 'duration_sum' | 'count' | 'credit'
  desc: boolean
}
