/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ReportSaveConnections {
  method: 'report.saveConnections'
  auth_type?: 'ADMIN'
  conds: {
    [k: string]: unknown
  }
  from: number
  to: number
  sort_by:
    | 'user_id'
    | 'credit_used'
    | 'login_time'
    | 'logout_time'
    | 'successful'
    | 'service'
    | 'ras_id'
    | 'connection_log_id'
  desc: boolean
}
