/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ListOfAdminUsernamesOrStringOfOneAdminUsername2 =
  | ListOfAdminUsernamesOrStringOfOneAdminUsername
  | ListOfAdminUsernamesOrStringOfOneAdminUsername1
export type ListOfAdminUsernamesOrStringOfOneAdminUsername = unknown[]
export type ListOfAdminUsernamesOrStringOfOneAdminUsername1 = string
export type ComesWithDepositOpCond = number
export type ComesWithDepositCond = '=' | '>' | '<' | '>=' | '<='
export type DatetimeOrNumber2 = DatetimeOrNumber | DatetimeOrNumber1
export type DatetimeOrNumber = string
export type DatetimeOrNumber1 = number
export type DatetimeOrNumber5 = DatetimeOrNumber3 | DatetimeOrNumber4
export type DatetimeOrNumber3 = string
export type DatetimeOrNumber4 = number
export type ListOfGroupNamesOrStringOfOneGroupName2 =
  | ListOfGroupNamesOrStringOfOneGroupName
  | ListOfGroupNamesOrStringOfOneGroupName1
export type ListOfGroupNamesOrStringOfOneGroupName = unknown[]
export type ListOfGroupNamesOrStringOfOneGroupName1 = string
export type ListOfIspNamesOrStringOneIspName2 = ListOfIspNamesOrStringOneIspName | ListOfIspNamesOrStringOneIspName1
export type ListOfIspNamesOrStringOneIspName = unknown[]
export type ListOfIspNamesOrStringOneIspName1 = string

export interface ReportGetUserDepositChanges {
  method: 'report.getUserDepositChanges'
  auth_type?: 'NORMAL_USER' | 'VOIP_USER'
  conds: {
    admin?: ListOfAdminUsernamesOrStringOfOneAdminUsername2
    action?: {
      [k: string]: unknown
    }[]
    deposit?: ComesWithDepositOpCond
    deposit_op?: ComesWithDepositCond
    change_time_from?: DatetimeOrNumber2
    change_time_from_unit?: 'jalali' | 'gregorian' | 'years' | 'months' | 'days' | 'hours' | 'minutes'
    change_time_to?: DatetimeOrNumber5
    change_time_to_unit?: 'jalali' | 'gregorian' | 'years' | 'months' | 'days' | 'hours' | 'minutes'
    remote_addr?: string
    group_name?: ListOfGroupNamesOrStringOfOneGroupName2
    isp_names?: ListOfIspNamesOrStringOneIspName2
    [k: string]: unknown
  }
  from: number
  to: number
  sort_by: 'change_time' | 'user_id' | 'deposit_change'
  desc: boolean
}
