/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserAddNewUsers {
  method: "user.addNewUsers";
  auth_type?: "ADMIN";
  count: number;
  credit: number;
  isp_name: string;
  group_name: string;
  credit_comment: string;
  custom_fields?: {
    [k: string]: unknown;
  };
}
