/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserKillMe {
  method: "user.killMe";
  auth_type?: "NORMAL_USER" | "VOIP_USER";
  unique_id_val: string;
  ras_ip: string;
}
