/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserGetUserInfo {
  method: 'user.getUserInfo'
  auth_type?: 'ADMIN'
  user_id?: string
  normal_username?: string
  voip_username?: string
  serial?: string
  phone?: string
  rempte_ip?: string
}
