/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserBulkChangeUserDeposit {
  method: "user.bulkChangeUserDeposit";
  auth_type?: "ADMIN";
  conds: {
    [k: string]: unknown;
  };
  deposit: number;
  change_type: "ADD" | "SET" | "MULTIPLY";
  deposit_comment: string;
}
