/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserSetOneChargeRuleUsage {
  method: "user.setOneChargeRuleUsage";
  auth_type?: "ADMIN";
  user_id: number;
  charge_rule_id: number;
  credit_usage: number;
  time_usage: number;
  traffic_usage: number;
}
