/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DatetimeOrNumber2 = DatetimeOrNumber | DatetimeOrNumber1;
export type DatetimeOrNumber = string;
export type DatetimeOrNumber1 = number;
export type DatetimeOrNumber5 = DatetimeOrNumber3 | DatetimeOrNumber4;
export type DatetimeOrNumber3 = string;
export type DatetimeOrNumber4 = number;
export type ListOfIspNamesOrStringOfOneIspName2 =
  | ListOfIspNamesOrStringOfOneIspName
  | ListOfIspNamesOrStringOfOneIspName1;
export type ListOfIspNamesOrStringOfOneIspName = unknown[];
export type ListOfIspNamesOrStringOfOneIspName1 = string;
export type ListOfGroupNamesOrStringOfOneGroupName2 =
  | ListOfGroupNamesOrStringOfOneGroupName
  | ListOfGroupNamesOrStringOfOneGroupName1;
export type ListOfGroupNamesOrStringOfOneGroupName = unknown[];
export type ListOfGroupNamesOrStringOfOneGroupName1 = string;
export type ListOfGroupNamesOrStringOfOneGroupName5 =
  | ListOfGroupNamesOrStringOfOneGroupName3
  | ListOfGroupNamesOrStringOfOneGroupName4;
export type ListOfGroupNamesOrStringOfOneGroupName3 = unknown[];
export type ListOfGroupNamesOrStringOfOneGroupName4 = string;

export interface UserSearchExpiredUsers {
  method: "user.searchExpiredUsers";
  auth_type?: "ADMIN";
  conds: {
    exp_date_from?: DatetimeOrNumber2;
    exp_date_from_unit?: "jalali" | "gregorian" | "years" | "months" | "days" | "hours" | "minutes";
    exp_date_to?: DatetimeOrNumber5;
    exp_date_to_unit?: "jalali" | "gregorian" | "years" | "months" | "days" | "hours" | "minutes";
    isp_names?: ListOfIspNamesOrStringOfOneIspName2;
    group_name?: ListOfGroupNamesOrStringOfOneGroupName2;
    not_in_group_name?: ListOfGroupNamesOrStringOfOneGroupName5;
    [k: string]: unknown;
  };
  from: number;
  to: number;
  order_by: "user_id" | "isp_id" | "group_id" | "creation_date" | "credit" | "Deposit";
  desc: boolean;
}
