/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserSetFeshfesheParams {
  method: 'user.setFeshfesheParams'
  auth_type?: 'ADMIN'
  user_id: number
  traffic: number
  date_from: string
  date_to: string
}
