/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CommentNameUserSRealName = string;
export type CommentPhone = string;
export type CommentCellPhoneNumber = string;
export type CommentEmail = string;
export type CommentAddress = string;
export type CommentDateOfBirth = string;

export interface UserUpdateUserComments {
  method: "user.updateUserComments";
  auth_type?: "NORMAL_USER" | "VOIP_USER";
  update_dic: {
    name?: CommentNameUserSRealName;
    phone?: CommentPhone;
    cell_phone?: CommentCellPhoneNumber;
    email?: CommentEmail;
    address?: CommentAddress;
    birthdate?: CommentDateOfBirth;
    [k: string]: unknown;
  };
}
