/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GroupUpdateGroup {
  method: 'group.updateGroup'
  auth_type: 'ADMIN'
  group_id: number
  group_name: string
  comment: string
}
