/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface LoginSearchAdminLoginHistory {
  method: 'login.searchAdminLoginHistory'
  auth_type: 'ADMIN'
  conds: unknown
  _from: number
  to: number
  sort_by: 'admin_login_history_id' | 'login_date'
  desc: boolean
}
