/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BwUpdateBwStaticIP {
  method: "bw.updateBwStaticIP";
  auth_type?: "ADMIN";
  static_ip_id: number;
  ip_addr: string;
  tx_leaf_name: string;
  rx_leaf_name: string;
}
