/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BwUpdateNode {
  method: 'bw.updateNode'
  auth_type?: 'ADMIN'
  node_id: number
  rate_kbits: number
  ceil_kbits: number
  priority: number
}
