/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface InvoiceProformaInvoicePaid {
  method: 'invoice.proformaInvoicePaid'
  auth_type?: 'ADMIN'
  pi_id_list: unknown[]
  paid_amount_list: unknown[]
  payment_comment_list: unknown[]
}
