/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface VoucherVoucherAddBatch {
  method: 'voucher.voucherAddBatch'
  auth_type?: 'ADMIN'
  batch_dict: {
    batch_name?: string
    is_locked?: boolean
    credit?: number
    can_recharge_user?: boolean
    can_create_user?: boolean
    change_target?: 'credit' | 'deposit' | 'deposit_recharge'
    allow_use_by_children_isp?: boolean
    comment?: string
    [k: string]: unknown
  }
  pin_prefix: string
  pin_len: number
  serial_prefix: string
  serial_start: number
  count: number
}
