/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ExtraChargeAddExtraChargeProfile {
  method: 'extra_charge.addExtraChargeProfile'
  auth_type: 'ADMIN'
  profile_name: string
  comment: string
  effective_hour: string
  rules: unknown[]
}
