/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UtilDeleteSavedReport {
  method: 'util.deleteSavedReport'
  auth_type?: 'ADMIN'
  report_auth: string
  report_type: string
  report_date: string
  report_status: 'started' | 'finished'
  report_format: 'csv' | 'pdf'
}
