/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface IspUpdateISP {
  method: "isp.updateISP";
  auth_type: "ADMIN";
  isp_id: number;
  isp_name: string;
  parent_isp_name: string;
  isp_has_deposit_limit: boolean;
  isp_mapped_user_id: number;
  isp_auth_domain: string;
  isp_web_domain: string;
  isp_email: string;
  prevent_neg_deposit_login: boolean;
  isp_comment: string;
  isp_failed_user_id: number;
  isp_locked: boolean;
}
