/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NotificationAddNotificationRule {
  method: 'notification.addNotificationRule'
  auth_type: 'ADMIN'
  notification_profile_id: number
  notification_type:
    | 'expiration_date'
    | 'credit'
    | 'renew'
    | 'birth_day'
    | 'online_payment'
    | 'first_login'
    | 'credit_change'
    | 'deposit_change'
  notification_threshold: number
  message_type: 'sms' | 'email' | 'email_to_isp' | 'ibsng_message' | 'url' | 'user_event'
  message_template: string
}
